# -*- coding: utf-8 -*-
"""The Heart Disease Classifier.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1g1S94oIpd1t9-ZDapYEbUUchySPGQew-
"""

import pandas as pd
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/heart-disease/processed.cleveland.data'
column_names = ['age','sex','cp','trestbps','chol','fbs','restecg','thalach','exang','oldpeak','slope','ca','thal','target']
df = pd.read_csv(url,header= None, names=column_names)
print(df.head())
print(df.tail())

df.info()

# The 'target' column is our answer key (0 = no disease, 1-4 = disease). Let's simplify it to a binary problem.
df ['target'] = df ['target'].apply(lambda x: 1 if x > 0 else 0)

# X contains all the columns we use for prediction
X = df.drop('target', axis=1)

# y contains only the column we want to predict
y = df ['target' ]

print("Shape of our features (X):", X.shape)
print("Shape of our target (y):", y.shape)

from sklearn.model_selection import train_test_split

# Split the data: 80% for training, 20% for testing
# random_state ensures we all get the same split for reproducibility
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2,
random_state=42)

print("Number of training samples:", X_train. shape [0])
print("Number of testing samples:", X_test.shape [0])

from sklearn. neighbors import KNeighborsClassifier
from sklearn. impute import SimpleImputer # New step to handle missing values
from sklearn.pipeline import Pipeline # To chain steps together

# The dataset has '?' for missing values. Let's handle this professionally.
# This pipeline will first replace missing values with the mean, then run the classifier.
# Note: This is a slightly more advanced but robust way to handle the data's imperfections.
import numpy as np
df. replace('?', np.nan, inplace=True) # Replace '?' with NaN so imputer can find it

# Recreate X and y after cleaning df so X reflects the NaN values
X = df.drop('target', axis=1)
y = df['']

X = X. astype(float) # Ensure all data is numeric for the imputer (now with NaN instead of '?')

# Redo the split with the cleaned data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2,
random_state=42)

# Build the model pipeline
model = Pipeline([
    ('imputer', SimpleImputer(strategy='mean')),
    ('knn', KNeighborsClassifier(n_neighbors=5))
])

# Train the model on the training data
model.fit(X_train, y_train)

print ("Model training complete!")

from sklearn.metrics import accuracy_score

# Use the trained model to make predictions on the unseen test data
predictions = model.predict(X_test)

# Compare the model's predictions to the actual answers
accuracy = accuracy_score(y_test, predictions)

print(f"Our model's accuracy on the test set is: {accuracy * 100 :.2f}%")

import matplotlib.pyplot as plt
from sklearn.neighbors import KNeighborsClassifier
from sklearn.impute import SimpleImputer
from sklearn.pipeline import Pipeline
from sklearn.metrics import accuracy_score

# Define a range of K values to test
k_values = range(1, 21) # Test K from 1 to 20
accuracies = []

for k in k_values:
    # Build the model pipeline for each k
    model_k = Pipeline([
        ('imputer', SimpleImputer(strategy='mean')),
        ('knn', KNeighborsClassifier(n_neighbors=k))
    ])

    # Train the model on the training data
    model_k.fit(X_train, y_train)

    # Use the trained model to make predictions on the unseen test data
    predictions_k = model_k.predict(X_test)

    # Calculate accuracy
    accuracy_k = accuracy_score(y_test, predictions_k)
    accuracies.append(accuracy_k)

# Plot the results
plt.figure(figsize=(10, 6))
plt.plot(k_values, accuracies, marker='o', linestyle='--')
plt.title('KNN Accuracy for Different Values of K')
plt.xlabel('K (Number of Neighbors)')
plt.ylabel('Accuracy on Test Set')
plt.xticks(list(k_values)) # Convert range to list for xticks
plt.grid(True)
plt.show()

# Print the best k and its accuracy
best_k = k_values[accuracies.index(max(accuracies))]
best_accuracy = max(accuracies)
print(f"The best K value is {best_k} with an accuracy of {best_accuracy * 100:.2f}%")